spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 20
      pool-name: HIKARICP
      register-mbeans: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jackson:
    time-zone: GMT
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    web:
      pageable:
        one-indexed-parameters: true
  sql:
    init:
      mode: never
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

server:
  port: 8081
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

springdoc:
  packages-to-scan: hjseo.boilerplate
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: path
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true